include_defs('//bucklets/maven_jar.bucklet')

VER = '2.11'
REPO = MAVEN_LOCAL

maven_jar(
  name = 'extension-api',
  id = 'com.google.gerrit:gerrit-extension-api:' + VER,
  attach_source = False,
  repository = REPO,
  license = 'Apache2.0',
)
